[package]
name = "nota-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nota"
path = "src/main.rs"

[dependencies]
nota-core = { path = "../nota-core" }
nota-infra = { path = "../nota-infra" }
nota-llm = { path = "../nota-llm" }
nota-onebot = { path = "../nota-onebot" }

anyhow.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
console.workspace = true
dirs.workspace = true
dialoguer.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
